package com.jiyun.greendaoduolianbiao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jiyun.greendaoduolianbiao.MuchStudent;
import com.jiyun.greendaoduolianbiao.MuchTeacher;
import com.jiyun.greendaoduolianbiao.One;
import com.jiyun.greendaoduolianbiao.Student;
import com.jiyun.greendaoduolianbiao.Teacher;
import com.jiyun.greendaoduolianbiao.TeacherJoinStudent;
import com.jiyun.greendaoduolianbiao.TwoStudent;

import com.jiyun.greendaoduolianbiao.dao.MuchStudentDao;
import com.jiyun.greendaoduolianbiao.dao.MuchTeacherDao;
import com.jiyun.greendaoduolianbiao.dao.OneDao;
import com.jiyun.greendaoduolianbiao.dao.StudentDao;
import com.jiyun.greendaoduolianbiao.dao.TeacherDao;
import com.jiyun.greendaoduolianbiao.dao.TeacherJoinStudentDao;
import com.jiyun.greendaoduolianbiao.dao.TwoStudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig muchStudentDaoConfig;
    private final DaoConfig muchTeacherDaoConfig;
    private final DaoConfig oneDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig teacherDaoConfig;
    private final DaoConfig teacherJoinStudentDaoConfig;
    private final DaoConfig twoStudentDaoConfig;

    private final MuchStudentDao muchStudentDao;
    private final MuchTeacherDao muchTeacherDao;
    private final OneDao oneDao;
    private final StudentDao studentDao;
    private final TeacherDao teacherDao;
    private final TeacherJoinStudentDao teacherJoinStudentDao;
    private final TwoStudentDao twoStudentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        muchStudentDaoConfig = daoConfigMap.get(MuchStudentDao.class).clone();
        muchStudentDaoConfig.initIdentityScope(type);

        muchTeacherDaoConfig = daoConfigMap.get(MuchTeacherDao.class).clone();
        muchTeacherDaoConfig.initIdentityScope(type);

        oneDaoConfig = daoConfigMap.get(OneDao.class).clone();
        oneDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        teacherJoinStudentDaoConfig = daoConfigMap.get(TeacherJoinStudentDao.class).clone();
        teacherJoinStudentDaoConfig.initIdentityScope(type);

        twoStudentDaoConfig = daoConfigMap.get(TwoStudentDao.class).clone();
        twoStudentDaoConfig.initIdentityScope(type);

        muchStudentDao = new MuchStudentDao(muchStudentDaoConfig, this);
        muchTeacherDao = new MuchTeacherDao(muchTeacherDaoConfig, this);
        oneDao = new OneDao(oneDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        teacherDao = new TeacherDao(teacherDaoConfig, this);
        teacherJoinStudentDao = new TeacherJoinStudentDao(teacherJoinStudentDaoConfig, this);
        twoStudentDao = new TwoStudentDao(twoStudentDaoConfig, this);

        registerDao(MuchStudent.class, muchStudentDao);
        registerDao(MuchTeacher.class, muchTeacherDao);
        registerDao(One.class, oneDao);
        registerDao(Student.class, studentDao);
        registerDao(Teacher.class, teacherDao);
        registerDao(TeacherJoinStudent.class, teacherJoinStudentDao);
        registerDao(TwoStudent.class, twoStudentDao);
    }
    
    public void clear() {
        muchStudentDaoConfig.clearIdentityScope();
        muchTeacherDaoConfig.clearIdentityScope();
        oneDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        teacherDaoConfig.clearIdentityScope();
        teacherJoinStudentDaoConfig.clearIdentityScope();
        twoStudentDaoConfig.clearIdentityScope();
    }

    public MuchStudentDao getMuchStudentDao() {
        return muchStudentDao;
    }

    public MuchTeacherDao getMuchTeacherDao() {
        return muchTeacherDao;
    }

    public OneDao getOneDao() {
        return oneDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

    public TeacherJoinStudentDao getTeacherJoinStudentDao() {
        return teacherJoinStudentDao;
    }

    public TwoStudentDao getTwoStudentDao() {
        return twoStudentDao;
    }

}
