package com.jiyun.greendaoduolianbiao.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.jiyun.greendaoduolianbiao.TeacherJoinStudent;

import com.jiyun.greendaoduolianbiao.MuchTeacher;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MUCH_TEACHER".
*/
public class MuchTeacherDao extends AbstractDao<MuchTeacher, Long> {

    public static final String TABLENAME = "MUCH_TEACHER";

    /**
     * Properties of entity MuchTeacher.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property TeacherId = new Property(0, Long.class, "teacherId", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
    }

    private DaoSession daoSession;

    private Query<MuchTeacher> muchStudent_TeacherBeanListQuery;

    public MuchTeacherDao(DaoConfig config) {
        super(config);
    }
    
    public MuchTeacherDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MUCH_TEACHER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: teacherId
                "\"NAME\" TEXT);"); // 1: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MUCH_TEACHER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MuchTeacher entity) {
        stmt.clearBindings();
 
        Long teacherId = entity.getTeacherId();
        if (teacherId != null) {
            stmt.bindLong(1, teacherId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MuchTeacher entity) {
        stmt.clearBindings();
 
        Long teacherId = entity.getTeacherId();
        if (teacherId != null) {
            stmt.bindLong(1, teacherId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
    }

    @Override
    protected final void attachEntity(MuchTeacher entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MuchTeacher readEntity(Cursor cursor, int offset) {
        MuchTeacher entity = new MuchTeacher( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // teacherId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MuchTeacher entity, int offset) {
        entity.setTeacherId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MuchTeacher entity, long rowId) {
        entity.setTeacherId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MuchTeacher entity) {
        if(entity != null) {
            return entity.getTeacherId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MuchTeacher entity) {
        return entity.getTeacherId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "teacherBeanList" to-many relationship of MuchStudent. */
    public List<MuchTeacher> _queryMuchStudent_TeacherBeanList(Long sId) {
        synchronized (this) {
            if (muchStudent_TeacherBeanListQuery == null) {
                QueryBuilder<MuchTeacher> queryBuilder = queryBuilder();
                queryBuilder.join(TeacherJoinStudent.class, TeacherJoinStudentDao.Properties.TId)
                    .where(TeacherJoinStudentDao.Properties.SId.eq(sId));
                muchStudent_TeacherBeanListQuery = queryBuilder.build();
            }
        }
        Query<MuchTeacher> query = muchStudent_TeacherBeanListQuery.forCurrentThread();
        query.setParameter(0, sId);
        return query.list();
    }

}
