package com.jiyun.greendaoduolianbiao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jiyun.greendaoduolianbiao.TeacherJoinStudent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEACHER_JOIN_STUDENT".
*/
public class TeacherJoinStudentDao extends AbstractDao<TeacherJoinStudent, Long> {

    public static final String TABLENAME = "TEACHER_JOIN_STUDENT";

    /**
     * Properties of entity TeacherJoinStudent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TId = new Property(1, Long.class, "tId", false, "T_ID");
        public final static Property SId = new Property(2, Long.class, "sId", false, "S_ID");
    }


    public TeacherJoinStudentDao(DaoConfig config) {
        super(config);
    }
    
    public TeacherJoinStudentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEACHER_JOIN_STUDENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"T_ID\" INTEGER," + // 1: tId
                "\"S_ID\" INTEGER);"); // 2: sId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEACHER_JOIN_STUDENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TeacherJoinStudent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long tId = entity.getTId();
        if (tId != null) {
            stmt.bindLong(2, tId);
        }
 
        Long sId = entity.getSId();
        if (sId != null) {
            stmt.bindLong(3, sId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TeacherJoinStudent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long tId = entity.getTId();
        if (tId != null) {
            stmt.bindLong(2, tId);
        }
 
        Long sId = entity.getSId();
        if (sId != null) {
            stmt.bindLong(3, sId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TeacherJoinStudent readEntity(Cursor cursor, int offset) {
        TeacherJoinStudent entity = new TeacherJoinStudent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // tId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // sId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TeacherJoinStudent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setSId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TeacherJoinStudent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TeacherJoinStudent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TeacherJoinStudent entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
